-- FORM Club backend schema (Supabase/Postgres 17 compatible)
-- Apply to a dedicated FORM/Trakiler project. Do not reuse an unrelated production database.

create schema if not exists private;

create table if not exists public.form_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null check (char_length(display_name) between 1 and 30),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.form_daily_activity (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  activity_date date not null default current_date,
  bodyweight_kg numeric(6,2) not null check (bodyweight_kg between 30 and 250),
  steps integer not null default 0 check (steps between 0 and 100000),
  active_minutes integer not null default 0 check (active_minutes between 0 and 600),
  completed_sets integer not null default 0 check (completed_sets between 0 and 80),
  total_volume_kg numeric(12,2) not null default 0 check (total_volume_kg between 0 and 1000000),
  streak_days integer not null default 1 check (streak_days between 0 and 3650),
  activity_score numeric(8,1) not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, activity_date)
);

create table if not exists public.form_public_daily_leaderboard (
  user_id uuid not null references auth.users(id) on delete cascade,
  activity_date date not null,
  display_name text not null,
  steps integer not null,
  active_minutes integer not null,
  completed_sets integer not null,
  total_volume_kg numeric(12,2) not null,
  streak_days integer not null,
  activity_score numeric(8,1) not null,
  updated_at timestamptz not null default now(),
  primary key (user_id, activity_date)
);

create index if not exists form_daily_activity_date_score_idx on public.form_daily_activity(activity_date, activity_score desc);
create index if not exists form_daily_activity_user_idx on public.form_daily_activity(user_id, activity_date desc);
create index if not exists form_public_leaderboard_date_score_idx on public.form_public_daily_leaderboard(activity_date, activity_score desc);

alter table public.form_profiles enable row level security;
alter table public.form_daily_activity enable row level security;
alter table public.form_public_daily_leaderboard enable row level security;

revoke all on public.form_profiles from anon, authenticated;
revoke all on public.form_daily_activity from anon, authenticated;
revoke all on public.form_public_daily_leaderboard from anon, authenticated;
grant select, insert, update on public.form_profiles to authenticated;
grant select, insert, update on public.form_daily_activity to authenticated;
grant select on public.form_public_daily_leaderboard to authenticated;
grant usage, select on sequence public.form_daily_activity_id_seq to authenticated;

create policy "form_profiles_select_own" on public.form_profiles for select to authenticated
using ((select auth.uid()) = user_id);
create policy "form_profiles_insert_own" on public.form_profiles for insert to authenticated
with check ((select auth.uid()) = user_id);
create policy "form_profiles_update_own" on public.form_profiles for update to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "form_activity_select_own" on public.form_daily_activity for select to authenticated
using ((select auth.uid()) = user_id);
create policy "form_activity_insert_own" on public.form_daily_activity for insert to authenticated
with check ((select auth.uid()) = user_id);
create policy "form_activity_update_own" on public.form_daily_activity for update to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "form_leaderboard_read" on public.form_public_daily_leaderboard for select to authenticated
using (true);

create or replace function private.form_activity_score(
  p_sets integer,
  p_volume numeric,
  p_bodyweight numeric,
  p_steps integer,
  p_minutes integer,
  p_streak integer
) returns numeric
language sql immutable
set search_path = ''
as $$
  select round((
    least(greatest(coalesce(p_sets,0),0),40) * 4.0
    + least(greatest(coalesce(p_volume,0) / greatest(coalesce(p_bodyweight,75),40),0),220) * 0.55
    + least(greatest(coalesce(p_minutes,0),0),180) * 0.55
    + least(greatest(coalesce(p_steps,0) / 1000.0,0),25) * 3.0
    + log(2, least(greatest(coalesce(p_streak,0),0),365) + 1) * 12.0
  )::numeric, 1)
$$;

create or replace function private.form_activity_before_write()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  if new.user_id is distinct from (select auth.uid()) then
    raise exception 'user_id must match authenticated user';
  end if;
  new.activity_score := private.form_activity_score(new.completed_sets,new.total_volume_kg,new.bodyweight_kg,new.steps,new.active_minutes,new.streak_days);
  new.updated_at := now();
  return new;
end;
$$;

create or replace function private.form_publish_leaderboard()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid uuid := (select auth.uid());
  v_name text;
begin
  if v_uid is null or new.user_id is distinct from v_uid then
    raise exception 'unauthorized FORM Club publish';
  end if;
  select p.display_name into v_name from public.form_profiles p where p.user_id = v_uid;
  if v_name is null then
    raise exception 'profile required before publishing';
  end if;
  insert into public.form_public_daily_leaderboard(user_id,activity_date,display_name,steps,active_minutes,completed_sets,total_volume_kg,streak_days,activity_score,updated_at)
  values(new.user_id,new.activity_date,v_name,new.steps,new.active_minutes,new.completed_sets,new.total_volume_kg,new.streak_days,new.activity_score,now())
  on conflict(user_id,activity_date) do update set
    display_name=excluded.display_name,steps=excluded.steps,active_minutes=excluded.active_minutes,completed_sets=excluded.completed_sets,total_volume_kg=excluded.total_volume_kg,streak_days=excluded.streak_days,activity_score=excluded.activity_score,updated_at=now();
  return new;
end;
$$;

revoke all on function private.form_publish_leaderboard() from public;
revoke all on function private.form_activity_before_write() from public;
revoke all on function private.form_activity_score(integer,numeric,numeric,integer,integer,integer) from public;

drop trigger if exists form_activity_score_trigger on public.form_daily_activity;
create trigger form_activity_score_trigger before insert or update on public.form_daily_activity
for each row execute function private.form_activity_before_write();

drop trigger if exists form_activity_publish_trigger on public.form_daily_activity;
create trigger form_activity_publish_trigger after insert or update on public.form_daily_activity
for each row execute function private.form_publish_leaderboard();

-- New Supabase projects no longer automatically expose SQL-created tables to the Data API.
-- The explicit grants above are intentional. Keep RLS enabled.
-- Enable Anonymous Sign-Ins in Auth if you want zero-friction pseudonymous Club identities.
