-- FORM backend schema — dedicated Supabase/Postgres project only.
-- Private-by-default training data; explicit public projection for opt-in Club ranking.

create schema if not exists private;

create table if not exists public.form_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default 'FORM athlete' check (char_length(display_name) between 1 and 30),
  goal text not null default 'general' check (goal in ('general','muscle','strength','recomp')),
  experience text not null default 'beginner' check (experience in ('beginner','intermediate','advanced')),
  training_days integer not null default 3 check (training_days between 2 and 6),
  session_minutes integer not null default 60 check (session_minutes between 25 and 180),
  equipment text not null default 'gym' check (equipment in ('gym','basic')),
  club_public boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.form_legal_acceptance (
  user_id uuid primary key references auth.users(id) on delete cascade,
  terms_version text not null,
  privacy_version text not null,
  accepted_at timestamptz not null default now()
);

create table if not exists public.form_workouts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  client_id text not null check (char_length(client_id) between 1 and 120),
  program_name text not null default '',
  day_name text not null default '',
  ended_at timestamptz not null,
  elapsed_sec integer not null default 0 check (elapsed_sec between 0 and 86400),
  completed_sets integer not null default 0 check (completed_sets between 0 and 100),
  total_sets integer not null default 0 check (total_sets between 0 and 100),
  total_volume_kg numeric(14,2) not null default 0 check (total_volume_kg between 0 and 5000000),
  notes text not null default '' check (char_length(notes) <= 4000),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id, client_id)
);

create table if not exists public.form_workout_sets (
  id bigint generated by default as identity primary key,
  workout_id uuid not null references public.form_workouts(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  set_index integer not null check (set_index between 1 and 100),
  exercise_id text not null check (char_length(exercise_id) between 1 and 100),
  exercise_name text not null default '' check (char_length(exercise_name) <= 100),
  weight_kg numeric(9,2) not null default 0 check (weight_kg between 0 and 2000),
  reps integer not null default 0 check (reps between 0 and 500),
  rir numeric(4,1) not null default 0 check (rir between 0 and 10),
  e1rm_kg numeric(10,2) generated always as (weight_kg * (1 + least(reps, 12)::numeric / 30)) stored,
  created_at timestamptz not null default now(),
  unique(workout_id, set_index)
);

create table if not exists public.form_body_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  log_date date not null default current_date,
  weight_kg numeric(6,2) check (weight_kg between 20 and 400),
  bodyfat_pct numeric(5,2) check (bodyfat_pct between 2 and 70),
  note text not null default '' check (char_length(note) <= 500),
  created_at timestamptz not null default now(),
  unique(user_id, log_date)
);

create table if not exists public.form_measurements (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  log_date date not null default current_date,
  waist_cm numeric(6,2), chest_cm numeric(6,2), shoulders_cm numeric(6,2), hips_cm numeric(6,2),
  left_arm_cm numeric(6,2), right_arm_cm numeric(6,2), left_thigh_cm numeric(6,2), right_thigh_cm numeric(6,2),
  left_calf_cm numeric(6,2), right_calf_cm numeric(6,2),
  created_at timestamptz not null default now(),
  unique(user_id, log_date),
  check (coalesce(waist_cm,1) between 1 and 300 and coalesce(chest_cm,1) between 1 and 300 and coalesce(shoulders_cm,1) between 1 and 300 and coalesce(hips_cm,1) between 1 and 300 and coalesce(left_arm_cm,1) between 1 and 300 and coalesce(right_arm_cm,1) between 1 and 300 and coalesce(left_thigh_cm,1) between 1 and 300 and coalesce(right_thigh_cm,1) between 1 and 300 and coalesce(left_calf_cm,1) between 1 and 300 and coalesce(right_calf_cm,1) between 1 and 300)
);

create table if not exists public.form_daily_activity (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  activity_date date not null default current_date,
  bodyweight_kg numeric(6,2) not null check (bodyweight_kg between 30 and 250),
  steps integer not null default 0 check (steps between 0 and 100000),
  active_minutes integer not null default 0 check (active_minutes between 0 and 600),
  completed_sets integer not null default 0 check (completed_sets between 0 and 80),
  total_volume_kg numeric(12,2) not null default 0 check (total_volume_kg between 0 and 1000000),
  streak_days integer not null default 1 check (streak_days between 1 and 3650),
  activity_score numeric(8,1) not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, activity_date)
);

create table if not exists public.form_public_daily_leaderboard (
  user_id uuid not null references auth.users(id) on delete cascade,
  activity_date date not null,
  display_name text not null,
  steps integer not null,
  active_minutes integer not null,
  completed_sets integer not null,
  total_volume_kg numeric(12,2) not null,
  streak_days integer not null,
  activity_score numeric(8,1) not null,
  updated_at timestamptz not null default now(),
  primary key (user_id, activity_date)
);

create index if not exists form_workouts_user_date_idx on public.form_workouts(user_id, ended_at desc);
create index if not exists form_sets_user_exercise_idx on public.form_workout_sets(user_id, exercise_id, created_at desc);
create index if not exists form_body_user_date_idx on public.form_body_logs(user_id, log_date desc);
create index if not exists form_measure_user_date_idx on public.form_measurements(user_id, log_date desc);
create index if not exists form_daily_activity_date_score_idx on public.form_daily_activity(activity_date, activity_score desc);
create index if not exists form_public_leaderboard_date_score_idx on public.form_public_daily_leaderboard(activity_date, activity_score desc);

alter table public.form_profiles enable row level security;
alter table public.form_legal_acceptance enable row level security;
alter table public.form_workouts enable row level security;
alter table public.form_workout_sets enable row level security;
alter table public.form_body_logs enable row level security;
alter table public.form_measurements enable row level security;
alter table public.form_daily_activity enable row level security;
alter table public.form_public_daily_leaderboard enable row level security;

revoke all on public.form_profiles, public.form_legal_acceptance, public.form_workouts, public.form_workout_sets, public.form_body_logs, public.form_measurements, public.form_daily_activity, public.form_public_daily_leaderboard from anon, authenticated;
grant select, insert, update, delete on public.form_profiles, public.form_legal_acceptance, public.form_workouts, public.form_workout_sets, public.form_body_logs, public.form_measurements, public.form_daily_activity to authenticated;
grant select on public.form_public_daily_leaderboard to anon, authenticated;
grant usage, select on sequence public.form_workout_sets_id_seq, public.form_body_logs_id_seq, public.form_measurements_id_seq, public.form_daily_activity_id_seq to authenticated;

create policy "profiles_own_select" on public.form_profiles for select to authenticated using ((select auth.uid()) = user_id);
create policy "profiles_own_insert" on public.form_profiles for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "profiles_own_update" on public.form_profiles for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "profiles_own_delete" on public.form_profiles for delete to authenticated using ((select auth.uid()) = user_id);

create policy "legal_own_select" on public.form_legal_acceptance for select to authenticated using ((select auth.uid()) = user_id);
create policy "legal_own_insert" on public.form_legal_acceptance for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "legal_own_update" on public.form_legal_acceptance for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "legal_own_delete" on public.form_legal_acceptance for delete to authenticated using ((select auth.uid()) = user_id);

create policy "workouts_own_select" on public.form_workouts for select to authenticated using ((select auth.uid()) = user_id);
create policy "workouts_own_insert" on public.form_workouts for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "workouts_own_update" on public.form_workouts for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "workouts_own_delete" on public.form_workouts for delete to authenticated using ((select auth.uid()) = user_id);

create policy "sets_own_select" on public.form_workout_sets for select to authenticated using ((select auth.uid()) = user_id and exists(select 1 from public.form_workouts w where w.id=workout_id and w.user_id=(select auth.uid())));
create policy "sets_own_insert" on public.form_workout_sets for insert to authenticated with check ((select auth.uid()) = user_id and exists(select 1 from public.form_workouts w where w.id=workout_id and w.user_id=(select auth.uid())));
create policy "sets_own_update" on public.form_workout_sets for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id and exists(select 1 from public.form_workouts w where w.id=workout_id and w.user_id=(select auth.uid())));
create policy "sets_own_delete" on public.form_workout_sets for delete to authenticated using ((select auth.uid()) = user_id);

create policy "body_own_all_select" on public.form_body_logs for select to authenticated using ((select auth.uid()) = user_id);
create policy "body_own_insert" on public.form_body_logs for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "body_own_update" on public.form_body_logs for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "body_own_delete" on public.form_body_logs for delete to authenticated using ((select auth.uid()) = user_id);

create policy "measure_own_select" on public.form_measurements for select to authenticated using ((select auth.uid()) = user_id);
create policy "measure_own_insert" on public.form_measurements for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "measure_own_update" on public.form_measurements for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "measure_own_delete" on public.form_measurements for delete to authenticated using ((select auth.uid()) = user_id);

create policy "activity_own_select" on public.form_daily_activity for select to authenticated using ((select auth.uid()) = user_id);
create policy "activity_own_insert" on public.form_daily_activity for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "activity_own_update" on public.form_daily_activity for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "activity_own_delete" on public.form_daily_activity for delete to authenticated using ((select auth.uid()) = user_id);

create policy "leaderboard_public_read" on public.form_public_daily_leaderboard for select to anon, authenticated using (true);

create or replace function private.form_activity_score(p_sets integer,p_volume numeric,p_bodyweight numeric,p_steps integer,p_minutes integer,p_streak integer) returns numeric language sql immutable set search_path='' as $$
  select round((least(greatest(coalesce(p_sets,0),0),40)*4.0 + least(greatest(coalesce(p_volume,0)/greatest(coalesce(p_bodyweight,75),40),0),220)*0.55 + least(greatest(coalesce(p_minutes,0),0),180)*0.55 + least(greatest(coalesce(p_steps,0)/1000.0,0),25)*3.0 + log(2,least(greatest(coalesce(p_streak,0),0),365)+1)*12.0)::numeric,1)
$$;

create or replace function private.form_activity_before_write() returns trigger language plpgsql security invoker set search_path='' as $$
declare v_prev integer;
begin
  if new.user_id is distinct from (select auth.uid()) then raise exception 'user_id must match authenticated user'; end if;
  select a.streak_days into v_prev from public.form_daily_activity a where a.user_id=new.user_id and a.activity_date=new.activity_date-1;
  if tg_op='INSERT' or new.activity_date is distinct from old.activity_date then new.streak_days:=coalesce(v_prev,0)+1; end if;
  new.activity_score:=private.form_activity_score(new.completed_sets,new.total_volume_kg,new.bodyweight_kg,new.steps,new.active_minutes,new.streak_days);
  new.updated_at:=now(); return new;
end; $$;

create or replace function private.form_publish_leaderboard() returns trigger language plpgsql security definer set search_path='' as $$
declare v_uid uuid:=(select auth.uid()); v_name text; v_public boolean;
begin
  if v_uid is null or new.user_id is distinct from v_uid then raise exception 'unauthorized FORM Club publish'; end if;
  select p.display_name,p.club_public into v_name,v_public from public.form_profiles p where p.user_id=v_uid;
  if coalesce(v_public,false)=false then
    delete from public.form_public_daily_leaderboard where user_id=v_uid;
    return new;
  end if;
  insert into public.form_public_daily_leaderboard(user_id,activity_date,display_name,steps,active_minutes,completed_sets,total_volume_kg,streak_days,activity_score,updated_at)
  values(new.user_id,new.activity_date,v_name,new.steps,new.active_minutes,new.completed_sets,new.total_volume_kg,new.streak_days,new.activity_score,now())
  on conflict(user_id,activity_date) do update set display_name=excluded.display_name,steps=excluded.steps,active_minutes=excluded.active_minutes,completed_sets=excluded.completed_sets,total_volume_kg=excluded.total_volume_kg,streak_days=excluded.streak_days,activity_score=excluded.activity_score,updated_at=now();
  return new;
end; $$;

create or replace function private.form_profile_privacy_sync() returns trigger language plpgsql security definer set search_path='' as $$
begin
  if new.user_id is distinct from (select auth.uid()) then raise exception 'unauthorized profile update'; end if;
  new.updated_at:=now();
  if new.club_public=false then delete from public.form_public_daily_leaderboard where user_id=new.user_id;
  elsif old.display_name is distinct from new.display_name then update public.form_public_daily_leaderboard set display_name=new.display_name,updated_at=now() where user_id=new.user_id; end if;
  return new;
end; $$;

revoke all on function private.form_activity_score(integer,numeric,numeric,integer,integer,integer) from public;
revoke all on function private.form_activity_before_write() from public;
revoke all on function private.form_publish_leaderboard() from public;
revoke all on function private.form_profile_privacy_sync() from public;

drop trigger if exists form_activity_score_trigger on public.form_daily_activity;
create trigger form_activity_score_trigger before insert or update on public.form_daily_activity for each row execute function private.form_activity_before_write();
drop trigger if exists form_activity_publish_trigger on public.form_daily_activity;
create trigger form_activity_publish_trigger after insert or update on public.form_daily_activity for each row execute function private.form_publish_leaderboard();
drop trigger if exists form_profile_privacy_trigger on public.form_profiles;
create trigger form_profile_privacy_trigger before update on public.form_profiles for each row execute function private.form_profile_privacy_sync();

-- Enable Anonymous Sign-Ins for private pseudonymous identities if desired.
-- The frontend may contain only the public project URL and publishable/anon-compatible key.
-- Never expose the service-role key in browser code. Account deletion is handled by the protected Edge Function in supabase/functions/delete-account.
