-- FORM v4 decision-support data. Apply after supabase/schema.sql.
-- All rows are private to the authenticated user. Nothing here is projected to Club.

create table if not exists public.form_coach_preferences (
  user_id uuid primary key references auth.users(id) on delete cascade,
  default_time_minutes integer not null default 60 check (default_time_minutes between 15 and 180),
  muscle_priorities jsonb not null default '{}'::jsonb,
  exercise_preferences jsonb not null default '{}'::jsonb,
  constraints jsonb not null default '[]'::jsonb,
  updated_at timestamptz not null default now(),
  check (jsonb_typeof(muscle_priorities)='object'),
  check (jsonb_typeof(exercise_preferences)='object'),
  check (jsonb_typeof(constraints)='array')
);

create table if not exists public.form_readiness_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  log_date date not null default current_date,
  sleep_quality smallint not null check (sleep_quality between 1 and 5),
  energy smallint not null check (energy between 1 and 5),
  stress smallint not null check (stress between 1 and 5),
  soreness smallint not null check (soreness between 0 and 3),
  motivation smallint not null check (motivation between 1 and 5),
  joint_discomfort smallint not null default 0 check (joint_discomfort between 0 and 3),
  available_minutes smallint not null default 60 check (available_minutes between 10 and 180),
  readiness_score numeric(5,1) generated always as (
    round((
      ((sleep_quality-1)::numeric/4)*24 +
      ((energy-1)::numeric/4)*26 +
      (1-((stress-1)::numeric/4))*18 +
      (1-(soreness::numeric/3))*17 +
      ((motivation-1)::numeric/4)*15
    ),1)
  ) stored,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id, log_date)
);

create index if not exists form_readiness_user_date_idx on public.form_readiness_logs(user_id, log_date desc);

alter table public.form_coach_preferences enable row level security;
alter table public.form_readiness_logs enable row level security;

revoke all on public.form_coach_preferences, public.form_readiness_logs from anon, authenticated;
grant select, insert, update, delete on public.form_coach_preferences, public.form_readiness_logs to authenticated;
grant usage, select on sequence public.form_readiness_logs_id_seq to authenticated;

create policy "coach_prefs_own_select" on public.form_coach_preferences for select to authenticated using ((select auth.uid())=user_id);
create policy "coach_prefs_own_insert" on public.form_coach_preferences for insert to authenticated with check ((select auth.uid())=user_id);
create policy "coach_prefs_own_update" on public.form_coach_preferences for update to authenticated using ((select auth.uid())=user_id) with check ((select auth.uid())=user_id);
create policy "coach_prefs_own_delete" on public.form_coach_preferences for delete to authenticated using ((select auth.uid())=user_id);

create policy "readiness_own_select" on public.form_readiness_logs for select to authenticated using ((select auth.uid())=user_id);
create policy "readiness_own_insert" on public.form_readiness_logs for insert to authenticated with check ((select auth.uid())=user_id);
create policy "readiness_own_update" on public.form_readiness_logs for update to authenticated using ((select auth.uid())=user_id) with check ((select auth.uid())=user_id);
create policy "readiness_own_delete" on public.form_readiness_logs for delete to authenticated using ((select auth.uid())=user_id);

create or replace function private.form_readiness_guard() returns trigger
language plpgsql security invoker set search_path='' as $$
begin
  if new.user_id is distinct from (select auth.uid()) then raise exception 'user_id must match authenticated user'; end if;
  new.updated_at:=now();
  return new;
end; $$;

create or replace function private.form_coach_prefs_guard() returns trigger
language plpgsql security invoker set search_path='' as $$
begin
  if new.user_id is distinct from (select auth.uid()) then raise exception 'user_id must match authenticated user'; end if;
  new.updated_at:=now();
  return new;
end; $$;

revoke all on function private.form_readiness_guard() from public;
revoke all on function private.form_coach_prefs_guard() from public;

drop trigger if exists form_readiness_guard_trigger on public.form_readiness_logs;
create trigger form_readiness_guard_trigger before insert or update on public.form_readiness_logs for each row execute function private.form_readiness_guard();
drop trigger if exists form_coach_prefs_guard_trigger on public.form_coach_preferences;
create trigger form_coach_prefs_guard_trigger before insert or update on public.form_coach_preferences for each row execute function private.form_coach_prefs_guard();