(()=>{
'use strict';
const D=window.FORM_DATA||{};const EX=D.exercises||{};
const entries=Object.entries(EX).map(([id,e])=>({id,name:e.name||id,category:e.category||'',equipment:e.equipment||'',primary:e.primary||[],secondary:e.secondary||[],score:Number(e.score||0)}));
const norm=s=>String(s||'').toLowerCase().trim();
function rank(q,x){q=norm(q);if(!q)return x.score/100;const name=norm(x.name),cat=norm(x.category),eq=norm(x.equipment),mus=norm([...x.primary,...x.secondary].join(' '));let s=0;if(name===q)s+=120;if(name.startsWith(q))s+=90;if(name.split(/\s+/).some(w=>w.startsWith(q)))s+=60;if(name.includes(q))s+=45;if(cat.includes(q))s+=24;if(eq.includes(q))s+=18;if(mus.includes(q))s+=28;s+=x.score/20;return s}
function matches(q){q=norm(q);return entries.map(x=>({...x,_r:rank(q,x)})).filter(x=>!q||x._r>10).sort((a,b)=>b._r-a._r||b.score-a.score||a.name.localeCompare(b.name)).slice(0,10)}
function menuFor(input,{onPick,meta=true}={}){let menu=null,items=[],active=-1;const host=input.parentElement;host.classList.add('typeahead-host');function close(){menu?.remove();menu=null;active=-1}function draw(){const q=input.value;items=matches(q);close();menu=document.createElement('div');menu.className='typeahead-menu';menu.setAttribute('role','listbox');if(!items.length){menu.innerHTML='<div class="typeahead-empty">No close exercise match. Try a muscle, equipment type, or shorter name.</div>'}else{menu.innerHTML=items.map((x,i)=>`<button type="button" class="typeahead-item" data-i="${i}" role="option"><span><b>${escapeHtml(x.name)}</b>${meta?`<span>${escapeHtml(x.category)} · ${escapeHtml(x.equipment)} · ${escapeHtml([...x.primary,...x.secondary].slice(0,3).join(', '))}</span>`:''}</span><em>FORM ${x.score}</em></button>`).join('');menu.querySelectorAll('.typeahead-item').forEach(b=>b.addEventListener('mousedown',e=>{e.preventDefault();pick(Number(b.dataset.i))}))}host.appendChild(menu)}function pick(i){const x=items[i];if(!x)return;input.value=x.name;close();onPick?.(x);input.dispatchEvent(new Event('input',{bubbles:true}));input.dispatchEvent(new Event('change',{bubbles:true}))}input.setAttribute('autocomplete','off');input.setAttribute('aria-autocomplete','list');input.addEventListener('focus',()=>draw());input.addEventListener('input',()=>draw());input.addEventListener('keydown',e=>{if(!menu&&(e.key==='ArrowDown'||e.key==='ArrowUp'))draw();const buttons=menu?[...menu.querySelectorAll('.typeahead-item')]:[];if(e.key==='ArrowDown'&&buttons.length){e.preventDefault();active=Math.min(active+1,buttons.length-1);buttons.forEach((b,i)=>b.classList.toggle('active',i===active));buttons[active]?.scrollIntoView({block:'nearest'})}else if(e.key==='ArrowUp'&&buttons.length){e.preventDefault();active=Math.max(active-1,0);buttons.forEach((b,i)=>b.classList.toggle('active',i===active));buttons[active]?.scrollIntoView({block:'nearest'})}else if(e.key==='Enter'&&active>=0){e.preventDefault();pick(active)}else if(e.key==='Escape')close()});input.addEventListener('blur',()=>setTimeout(close,120));return{draw,close}}
function escapeHtml(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function enhanceLibrary(){const input=document.querySelector('#exerciseSearch');if(!input||input.dataset.assisted)return;input.dataset.assisted='1';input.placeholder='Search exercise, muscle, equipment, or movement…';menuFor(input,{onPick:x=>{input.value=x.name;document.querySelector('#categoryFilter')&&(document.querySelector('#categoryFilter').value='')}})}
function enhanceEditor(){document.querySelectorAll('.ed-ex').forEach(select=>{if(select.dataset.assisted)return;select.dataset.assisted='1';const current=select.options[select.selectedIndex]?.textContent||'';const input=document.createElement('input');input.type='text';input.className='assist-exercise-input';input.value=current;input.placeholder='Search exercise, muscle, or equipment';select.classList.add('assist-hidden-select');select.parentElement.insertBefore(input,select);menuFor(input,{onPick:x=>{select.value=x.id;select.dispatchEvent(new Event('change',{bubbles:true}))}});input.addEventListener('blur',()=>{const exact=entries.find(x=>norm(x.name)===norm(input.value));if(exact)select.value=exact.id;else input.value=select.options[select.selectedIndex]?.textContent||current})})}
function boot(){enhanceLibrary();enhanceEditor();const obs=new MutationObserver(()=>{enhanceLibrary();enhanceEditor()});obs.observe(document.body,{childList:true,subtree:true})}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
