(()=>{
  const cfg=window.FORM_SUPABASE||{};
  const connected=()=>Boolean(cfg.url&&cfg.key&&window.supabase?.createClient);
  let client=null,session=null;
  const today=()=>new Date().toISOString().slice(0,10);
  const safe=(n,min,max)=>Math.min(max,Math.max(min,Number(n)||0));
  function sb(){if(!connected())return null;if(!client)client=window.supabase.createClient(cfg.url,cfg.key,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});return client}
  async function ensureUser(){const c=sb();if(!c)return null;if(session?.user)return session.user;const got=await c.auth.getSession();if(got.error)throw got.error;session=got.data.session;if(!session){const r=await c.auth.signInAnonymously();if(r.error)throw r.error;session=r.data.session}return session?.user||null}
  async function authState(){const c=sb();if(!c)return{connected:false,user:null};try{const u=await ensureUser();return{connected:true,user:u,anonymous:Boolean(u?.is_anonymous),email:u?.email||null}}catch(error){return{connected:true,user:null,error:error.message}}}
  async function magicLink(email){const c=sb();if(!c)throw new Error('FORM cloud sync is not configured.');email=String(email||'').trim();if(!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(email))throw new Error('Enter a valid email address.');const r=await c.auth.signInWithOtp({email,options:{emailRedirectTo:location.href}});if(r.error)throw r.error;return true}
  async function signOut(){const c=sb();if(!c)return;await c.auth.signOut();session=null}
  async function syncProfile(p={}){const c=sb(),u=await ensureUser();if(!c||!u)return null;const row={user_id:u.id,display_name:String(p.displayName||'FORM athlete').trim().slice(0,30)||'FORM athlete',goal:p.goal||'general',experience:p.experience||'beginner',training_days:safe(p.days||3,2,6),session_minutes:safe(p.sessionMinutes||60,25,180),equipment:p.equipment||'gym',club_public:Boolean(p.clubPublic),updated_at:new Date().toISOString()};const r=await c.from('form_profiles').upsert(row,{onConflict:'user_id'}).select('*').single();if(r.error)throw r.error;return r.data}
  async function getProfile(){const c=sb(),u=await ensureUser();if(!c||!u)return null;const r=await c.from('form_profiles').select('*').eq('user_id',u.id).maybeSingle();if(r.error)throw r.error;return r.data}
  async function acceptLegal(termsVersion='2026-08-08',privacyVersion='2026-08-08'){const c=sb(),u=await ensureUser();if(!c||!u)return null;const r=await c.from('form_legal_acceptance').upsert({user_id:u.id,terms_version:termsVersion,privacy_version:privacyVersion,accepted_at:new Date().toISOString()},{onConflict:'user_id'});if(r.error)throw r.error;return true}
  async function syncWorkout(w){const c=sb(),u=await ensureUser();if(!c||!u||!w)return null;const workout={user_id:u.id,client_id:String(w.id),program_name:String(w.program||''),day_name:String(w.day||''),ended_at:w.endedAt||new Date().toISOString(),elapsed_sec:safe(w.elapsedSec,0,86400),completed_sets:safe(w.completedSets,0,100),total_sets:safe(w.totalSets,0,100),total_volume_kg:safe(w.volume,0,5000000),notes:String(w.notes||'').slice(0,4000)};const wr=await c.from('form_workouts').upsert(workout,{onConflict:'user_id,client_id'}).select('id').single();if(wr.error)throw wr.error;const wid=wr.data.id;const del=await c.from('form_workout_sets').delete().eq('workout_id',wid);if(del.error)throw del.error;const sets=(w.sets||[]).map((x,i)=>({workout_id:wid,user_id:u.id,set_index:i+1,exercise_id:String(x.exerciseId||''),exercise_name:String(x.exercise||'').slice(0,100),weight_kg:safe(x.weight,0,2000),reps:safe(x.reps,0,500),rir:safe(x.rir,0,10)}));if(sets.length){const sr=await c.from('form_workout_sets').insert(sets);if(sr.error)throw sr.error}return wid}
  async function syncBodyLog(x){const c=sb(),u=await ensureUser();if(!c||!u)return null;const row={user_id:u.id,log_date:x.date||today(),weight_kg:x.weight?safe(x.weight,20,400):null,bodyfat_pct:x.bodyfat===''||x.bodyfat==null?null:safe(x.bodyfat,2,70),note:String(x.note||'').slice(0,500)};const r=await c.from('form_body_logs').upsert(row,{onConflict:'user_id,log_date'});if(r.error)throw r.error;return true}
  async function syncMeasurement(x){const c=sb(),u=await ensureUser();if(!c||!u)return null;const row={user_id:u.id,log_date:x.date||today()};for(const k of ['waist_cm','chest_cm','shoulders_cm','hips_cm','left_arm_cm','right_arm_cm','left_thigh_cm','right_thigh_cm','left_calf_cm','right_calf_cm'])row[k]=x[k]===''||x[k]==null?null:safe(x[k],1,300);const r=await c.from('form_measurements').upsert(row,{onConflict:'user_id,log_date'});if(r.error)throw r.error;return true}
  async function syncReadiness(x){const c=sb(),u=await ensureUser();if(!c||!u)return null;const row={user_id:u.id,log_date:x.date||today(),sleep_quality:safe(x.sleep,1,5),energy:safe(x.energy,1,5),stress:safe(x.stress,1,5),soreness:safe(x.soreness,0,3),motivation:safe(x.motivation,1,5),joint_discomfort:safe(x.joint,0,3),available_minutes:safe(x.time,10,180)};const r=await c.from('form_readiness_logs').upsert(row,{onConflict:'user_id,log_date'}).select('*').single();if(r.error)throw r.error;return r.data}
  async function syncCoachPreferences(p={}){const c=sb(),u=await ensureUser();if(!c||!u)return null;const row={user_id:u.id,default_time_minutes:safe(p.defaultTime||60,15,180),muscle_priorities:p.muscles||{},exercise_preferences:p.exercise||{},constraints:Array.isArray(p.constraints)?p.constraints.slice(0,20):[],updated_at:new Date().toISOString()};const r=await c.from('form_coach_preferences').upsert(row,{onConflict:'user_id'}).select('*').single();if(r.error)throw r.error;return r.data}
  async function publishActivity(x){const c=sb(),u=await ensureUser();if(!c||!u)return null;const r=await c.from('form_daily_activity').upsert({user_id:u.id,activity_date:today(),bodyweight_kg:safe(x.bodyweight||75,30,250),steps:safe(x.steps,0,100000),active_minutes:safe(x.minutes,0,600),completed_sets:safe(x.sets,0,80),total_volume_kg:safe(x.volume,0,1000000)},{onConflict:'user_id,activity_date'}).select('*').single();if(r.error)throw r.error;return r.data}
  async function leaderboard(){const c=sb();if(!c)return null;const r=await c.from('form_public_daily_leaderboard').select('*').eq('activity_date',today()).order('activity_score',{ascending:false}).limit(100);if(r.error)throw r.error;return r.data||[]}
  async function pullAll(){const c=sb(),u=await ensureUser();if(!c||!u)return null;const base=[c.from('form_profiles').select('*').eq('user_id',u.id).maybeSingle(),c.from('form_workouts').select('*').eq('user_id',u.id).order('ended_at'),c.from('form_workout_sets').select('*').eq('user_id',u.id),c.from('form_body_logs').select('*').eq('user_id',u.id).order('log_date'),c.from('form_measurements').select('*').eq('user_id',u.id).order('log_date'),c.from('form_legal_acceptance').select('*').eq('user_id',u.id).maybeSingle()];const [p,w,s,b,m,l]=await Promise.all(base);for(const x of [p,w,s,b,m,l])if(x.error)throw x.error;let readiness=[],coachPreferences=null;try{const r=await c.from('form_readiness_logs').select('*').eq('user_id',u.id).order('log_date');if(!r.error)readiness=r.data||[]}catch{}try{const cp=await c.from('form_coach_preferences').select('*').eq('user_id',u.id).maybeSingle();if(!cp.error)coachPreferences=cp.data||null}catch{}return{profile:p.data,workouts:w.data||[],sets:s.data||[],body:b.data||[],measurements:m.data||[],legal:l.data,readiness,coachPreferences}}
  async function deleteAccount(){const c=sb();if(!c)throw new Error('Cloud account is not configured.');const u=await ensureUser();if(!u)throw new Error('No cloud account.');const r=await c.functions.invoke('delete-account',{body:{confirm:'DELETE FORM ACCOUNT'}});if(r.error)throw r.error;await c.auth.signOut();session=null;return true}
  window.FORM_BACKEND={connected,authState,ensureUser,magicLink,signOut,syncProfile,getProfile,acceptLegal,syncWorkout,syncBodyLog,syncMeasurement,syncReadiness,syncCoachPreferences,publishActivity,leaderboard,pullAll,deleteAccount};
})();